version: '3.8'
services:
  backend:
    build: ./task-manager-backend
    ports:
      - "8080:8080"
    depends_on:
      - frontend

  frontend:
    build: ./task-manager-frontend
    ports:
      - "3000:80"
